// test/fixtures/emit-matrix.mjs -- generator for the README emit-support matrix.
//
// Reads test/fixtures/hashes.json (the checked-in sha256 manifest of every
// fixture source + compiled emit) and the INSTALLED toolchain versions, and
// renders the markdown block that lives in README.md between the
// <!-- EMIT-MATRIX:START --> / <!-- EMIT-MATRIX:END --> markers.
//
// The block is generated, never hand-typed: every sha256 comes from the
// manifest, every toolchain version from the resolved devDep. Drift is loud --
// test/04-fixture-freshness compares the README block against this output and
// fails on any mismatch. Package version is deliberately NOT embedded here: it
// is a three-place version site that later syncs to 1.0.0, and coupling a
// drift-checked doc block to it would break that bump (no test couples the
// version sites, by contract).
//
// ASCII-only. node:test-free (pure module + CLI). Run: node test/fixtures/emit-matrix.mjs

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { createRequire } from "node:module";

const HERE = dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);

function pkgVersion(name) {
    // Fail closed: an unresolvable toolchain dep is a generation error, never a
    // silent blank that would freeze a wrong matrix into the README.
    return require(name + "/package.json").version;
}

// Presentation order is fixed so the output is deterministic; each sha is
// pulled from the manifest by key (a missing key throws -- fail closed).
const ROWS = [
    { source: "fixture.src.ts", emitter: "TypeScript 5", lane: "standard 2023-11", out: "ts-out/fixture.src.js" },
    { source: "fixture.src.ts", emitter: "Babel", lane: "standard 2023-11", out: "babel-out/fixture.src.js" },
    { source: "static.src.ts", emitter: "TypeScript 5", lane: "standard 2023-11", out: "ts-out/static.src.js" },
    { source: "static.src.ts", emitter: "Babel", lane: "standard 2023-11", out: "babel-out/static.src.js" },
    { source: "legacy.src.ts", emitter: "TypeScript 5", lane: "legacy (experimental)", out: "ts-legacy-out/legacy.src.js" },
    { source: "legacy.src.ts", emitter: "Babel", lane: "legacy (experimental)", out: "babel-legacy-out/legacy.src.js" },
];

const SOURCES = ["fixture.src.ts", "static.src.ts", "legacy.src.ts"];

function verdict(source, lane) {
    if (lane.startsWith("legacy")) {
        return "rejected -- legacy emit -> named rejection at decoration time";
    }
    if (source.startsWith("static")) {
        return "rejected -- static member is a named throw at decoration time";
    }
    return "accepted -- full decorator surface wired + pinned green";
}

function short(hex) {
    return hex.slice(0, 12);
}

export function renderEmitMatrix() {
    const manifest = JSON.parse(
        readFileSync(join(HERE, "hashes.json"), "utf8"),
    );
    const need = (key) => {
        const v = manifest[key];
        if (typeof v !== "string") {
            throw new Error("emit-matrix: hashes.json is missing key '" + key + "'");
        }
        return v;
    };

    const ts = pkgVersion("typescript");
    const babelCore = pkgVersion("@babel/core");
    const babelDeco = pkgVersion("@babel/plugin-proposal-decorators");

    const lines = [];
    lines.push(
        "Generated by `node test/fixtures/emit-matrix.mjs` from " +
        "`test/fixtures/hashes.json` -- do not hand-edit. Toolchain pinned by the " +
        "committed fixtures: **TypeScript " + ts + "**, **@babel/core " + babelCore +
        "** + **@babel/plugin-proposal-decorators " + babelDeco +
        "** (`version: 2023-11`). Each `sha256` is the first 12 hex of the committed " +
        "emit; `npm run fixtures` regenerates and `test/04-fixture-freshness` fails " +
        "loudly on any drift.",
    );
    lines.push("");
    lines.push("| Source | Emitter | Emit lane | Compiled output | sha256 | At decoration time |");
    lines.push("|---|---|---|---|---|---|");
    for (const r of ROWS) {
        lines.push(
            "| `" + r.source + "` | " + r.emitter + " | " + r.lane + " | `" +
            r.out + "` | `" + short(need(r.out)) + "` | " +
            verdict(r.source, r.lane) + " |",
        );
    }
    lines.push("");
    lines.push(
        "Source hashes: " +
        SOURCES.map((s) => "`" + s + "` `" + short(need("src/" + s)) + "`").join(", ") +
        ".",
    );
    return lines.join("\n");
}

// CLI: print the block.
if (import.meta.url === "file://" + process.argv[1]) {
    process.stdout.write(renderEmitMatrix() + "\n");
}
